sudo: false

language: php
  - 7.0
  - 7.1
before_script:
  - phpenv config-rm xdebug.ini || return 0
  - pecl instal swoole
  - echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script:
  - composer run-script test


