sudo: true

services:
  - docker
before_install:
  - docker pull racecourse/courser
  - docker run -d racecourse/courser /bin/sh
  - docker ps -a
  - docker run racecourse/courser /bin/sh -c "composer run-script test"

script:
  - composer run-script test


